### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by mlanci** [unifiedfx/automationfx-python#2]
Trying to install and getting

Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-qfxu8cov/Enum/

Python 3.6.4

**Comment by stephenwelsh** [comment]
We have not tested on Python 3.6.4, we shall invesitage

I suggest you install the latest Python 2.7 version and see if that works

**Comment by stephenwelsh** [comment]
Investigating this error message it may be an issue with permissions or your installation of Python. I suggest you have a look that the following related issue for another library:

https://stackoverflow.com/questions/35991403/pip-install-returns-python-setup-py-egg-info-failed-with-error-code-1

**Comment by mlanci** [comment]
Edit: 2.7 is working now.

Would love to figure out what's going on in py3!

**Comment by stephenwelsh** [comment]
Closing this for now, we shall see if we can get it working in Python 3.6.4
