### ISSUE TITLE
Error running call method from SimpleCallTest

### ISSUE THREAD

**Issue by swatisharma023** [unifiedfx/automationfx-python#6]
I get this error while running this code: 
`from automationfx import *
import automationfx
from example_tests import SimpleCallTest, ConsultTransferTest

p1 = findPhone(Phone.DN == '231968')
p2 = findPhone(Phone.DN == '5078')
call(p1, p2.DN)
answer(p2)
pause(10)
drop(p1)

SimpleCallTest(p1, p2, 5)`

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://127.0.0.1:8181/AutomationFX/api/oData/Phones?%24top=1&%24filter=DN+eq+%27231968%27

Can you help me with this.

**Comment by mohamedaaquib** [comment]
Could you please create a Policy (Configuration > Policy in AutomationFX Admin inetrface) and assign Api permission or Full Admin permission.

Once the policy is created with apporpriate permission, you need to add the App (Search for the App name in member search box) as a member of the policy.

**Comment by swatisharma023** [comment]
![image](https://user-images.githubusercontent.com/6657959/74990158-5b2e2600-53f7-11ea-86d5-902b66ee8425.png)

This is the only admin interface i see. I dont see any configuration option on this
ANd one more question, what should be the value of AutomationFX Host: 10.10.11.178, should it be IP of the CUCM??

**Comment by mohamedaaquib** [comment]
Setup Issue handled directly with @swatisharma023 through the UnifiedFX support system.[sales@unifiedfx.com/support@unifiedfx.com]
