### ISSUE TITLE
OData error while running automationfx actions

### ISSUE THREAD

**Issue by swatisharma023** [unifiedfx/automationfx-python#7]
Hi, I am running automationfx to answer the calls on ipcommunicator using python. I see this error while running the actions. Although the code and actions (script) successfully work on my laptop, but when I am trying to run the same thing on another system, I continue to see this error. Is this something to do with the API key , which i generated on the web app on the new system and Phoneview is working as well. Can someone help me with this. Really appreciate. 

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://127.0.0.1:8181/AutomationFX/api/oData/Phones?%24top=1&%24filter=DN+eq+%27231974%27

c:\python37\lib\site-packages\requests\models.py:940: HTTPError

During handling of the above exception, another exception occurred:

    def test_outbound_call():
        
        test1.call_deskphone("231974")
        print ("User is calling the deskphone")
        p1 = findPhone(Phone.DN == '231974')

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\automationfx\actions\__init__.py:139: in findPhone
    return queryPhone().filter(param).first()
c:\python37\lib\site-packages\odata\query.py:271: in first
    data = list(iter(self))
c:\python37\lib\site-packages\odata\query.py:70: in __iter__
    data = self.connection.execute_get(url, options)
c:\python37\lib\site-packages\odata\connection.py:108: in execute_get
    self._handle_odata_error(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <odata.connection.ODataConnection object at 0x000001F0056B1CC8>, response = <Response [403]>

    ```
def _handle_odata_error(self, response):
        try:
            response.raise_for_status()
        except:
            status_code = 'HTTP {0}'.format(response.status_code)
            code = 'None'
            message = 'Server did not supply any error messages'
            detailed_message = 'None'
            response_ct = response.headers.get('content-type', '')

            if 'application/json' in response_ct:
                errordata = response.json()

                if 'error' in errordata:
                    odata_error = errordata.get('error')

                    if 'code' in odata_error:
                        code = odata_error.get('code') or code
                    if 'message' in odata_error:
                        message = odata_error.get('message') or message
                    if 'innererror' in odata_error:
                        ie = odata_error['innererror']
                        detailed_message = ie.get('message') or detailed_message

            msg = ' | '.join([status_code, code, message, detailed_message])
            err = ODataError(msg)
            err.status_code = status_code
            err.code = code
            err.message = message
            err.detailed_message = detailed_message

>           raise err
E           odata.exceptions.ODataError: HTTP 403 | None | Server did not supply any error messages | None

c:\python37\lib\site-packages\odata\connection.py:97: ODataError
```

**Comment by swatisharma023** [comment]
I was able to fix this 403 OData forbidden error by adding the app as members to the Admin policy. It works for me now. This was a permission issue. Thanks. 
![image](https://user-images.githubusercontent.com/6657959/83909319-6a727e80-a71d-11ea-89ad-12008c3dbd4a.png)

**Comment by stephenwelsh** [comment]
Glad you got it working,
Take care
