### ISSUE TITLE
Software License issue on the UI

### ISSUE THREAD

**Issue by swatisharma023** [unifiedfx/automationfx-python#8]
Hi,

I am using automation fx and phoneview for automation. When I try to access the unified fx UI from Phone view, on the UI it asks me for the software license key . I didnt see this before. I added my phone view license key there and it didnt work. Can you please help me with that. 

I am attaching the snapshot of the error. 
![image](https://user-images.githubusercontent.com/6657959/118155474-224be980-b3cd-11eb-8d51-97a6b9baa6d6.png)

**Comment by stephenwelsh** [comment]
Hi swatisharma023,

Sure we can assist, if you could contact support@unifiedfx.com, ideally with the email address you have linked to your license we can look into it.
